# Generated by Django 4.1.7 on 2023-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_motorista_empresa_empresa_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='motorista',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='home.motorista'),
        ),
    ]
