# Generated by Django 4.1.7 on 2023-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_empresa_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='motorista',
            field=models.ManyToManyField(blank=True, null=True, related_name='lista_empresas', to='home.motorista'),
        ),
    ]
