# Generated by Django 4.1.7 on 2023-03-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_empresa_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='motorista',
            field=models.ManyToManyField(blank=True, related_name='lista_empresas', to='home.motorista'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='home.cliente'),
        ),
    ]
