# Generated by Django 4.1.7 on 2023-03-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_empresa_motorista_alter_notafiscal_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
