# Generated by Django 4.1.7 on 2023-04-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='cliente',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente', verbose_name='Cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.endereco', verbose_name='Endereco')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.notafiscal', verbose_name='Nota Fiscal')),
            ],
        ),
    ]
