# Generated by Django 4.1.7 on 2023-04-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_cliente_lat_remove_cliente_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=12, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Compemento'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.endereco', verbose_name='Endereço'),
        ),
    ]
