# Generated by Django 4.1.7 on 2023-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_endereco_cep_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='latitude',
            field=models.FloatField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.FloatField(default=None, max_length=20, null=True),
        ),
    ]
